language: node_js
node_js:
  - "8"
  - "9"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
before_script:
  - npm install
script:
  - ng build --prod
  - travis_wait 10 ng test
